config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_closed', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :styles
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :places, only: [:index, :show]
  resource :session, only: [:new, :create, :destroy]
  root 'breweries#index'
  #get 'ratings',  to: 'ratings#index'
  #get 'ratings/new', to: 'ratings#new'
  #post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include RatingAverage

  has_secure_password
  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  validates :username,  uniqueness: true,
                        length: { minimum: 3, maximum: 30 }

  validates :password,  length: { minimum: 4 },
                        format: {
                          with: /[A-Z].*\d|\d.*[A-Z]/,
                          message: "Must contain at least one capital letter and number"
                        }

  def favorite_beer
    return nil if ratings.empty?

    ratings.order(score: :desc).limit(1).first.beer
  end

  def average_of(ratings)
    ratings.sum(&:score).to_f / ratings.count
  end

  def favorite_style
    favorite :style
  end

  def favorite_brewery
    favorite :brewery
  end

  def favorite(grouped_by)
    return nil if ratings.empty?

    grouped_ratings = ratings.group_by{ |r| r.beer.send(grouped_by) }
    averages = grouped_ratings.map do |group, ratings|
      { group: group, score: average_of(ratings) }
    end

    averages.max_by{ |r| r[:score] }[:group]
  end

  def self.top(count)
    sorted_by_rating_count_in_desc_order = User.all.sort_by{ |b| -(b.ratings.count || 0) }

    if count >= User.count
      sorted_by_rating_count_in_desc_order
    else
      sorted_by_rating_count_in_desc_order.take(count)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_admin_status, only: [:toggle_closed]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings, :beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? && @user == current_user && @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == current_user
      @user.destroy
      session[:user_id] = nil
    else
      respond_to do |format|
        format.html { redirect_to users_path, notice: 'Unauthorized action' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_closed
    user = User.find(params[:id])
    user.update_attribute :closed, !user.closed

    new_status = user.closed? ? "closed" : "open"

    redirect_to user, notice: "Account status changed to #{new_status}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>
  <% end %>  

  <div class="field">
    <%= form.label :password %><br />
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation  %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
 

<h1>Change password for <%= @user.username %></h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', @user, class:'btn btn-primary' %>

app/views/users/index.html.erb
 <h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th> Username </th>
      <th> Beers rated </th>
      <th> Total ratings </th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if current_user && current_user.admin && user.closed %>
            <span class="badge badge-info">Account closed</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, class:'btn btn-primary' %>

app/views/users/show.html.erb
<% if current_user && current_user.admin %>
  <% if @user.closed %>
     <h2>
      <%= @user.username %> <span class="badge badge-info">Account closed</span>
    </h2>
    <%= link_to 'Open account', toggle_closed_user_path(@user.id), method: :post, class: 'btn btn-primary' %>
  <% else %>
    <h2>
      <%= @user.username %>
    </h2> 
    <%= link_to 'Close account', toggle_closed_user_path(@user.id), method: :post, class:'btn btn-danger' %>
  <% end %>
<% else %>
   <h2>
    <%= @user.username %>
  </h2>  
<% end %>

<% if @user.ratings.empty? %>
  <p>Has not rated any beers yet</p>
<% else %>
  <p>
    Has made <%= pluralize(@user.ratings.count, 'rating') %> with the average score of <%= round(@user.average_rating) %>
  </p>
  <p> Favorite beer: <%= @user.favorite_beer.name %> </p>
  <p> Favorite brewery: <%= @user.favorite_brewery.name %> </p>
  <p> Preferred style: <%= @user.favorite_style.name %> </p>
<% end %>

<p>
  <% if @user.beer_clubs.any? %>
    Member of the following clubs:
    <% @user.beer_clubs.each do |club| %>
      <li>
        <%= link_to club.name, club %>
      </li>
    <% end %>
  <% end %>
</p>

<% if @user.ratings.any?%>
  <h3>
    Ratings
  </h3>

  <ul>
    <% @user.ratings.each do |rating| %>
      <li>
        <%= rating %> 
        <% if @user == current_user %>
          <%= link_to 'Delete rating', rating_path(rating.id), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></li>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if @user == current_user %>
  <%= link_to 'Change password', edit_user_path(@user), class:'btn btn-warning' %>
  <%= link_to 'Delete account', @user, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
<% end %>