config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_closed', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :styles
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :places, only: [:index, :show]
  resource :session, only: [:new, :create, :destroy]
  root 'breweries#index'
  #get 'ratings',  to: 'ratings#index'
  #get 'ratings/new', to: 'ratings#new'
  #post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage
  extend TopRated

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :name, presence: true
  validates :year, numericality: {  only_integer: true,
                                    greater_than_or_equal_to: 1040,
                                    less_than_or_equal_to: ->(_) { Time.now.year } }

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :ensure_admin_status, only: [:destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    return if request.format.html? && fragment_exist?('brewerylist')

    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    @breweries = Brewery.all

    order = params[:order] || 'name'
    @breweries =  case order
                  when 'name' then @breweries.sort_by(&:name)
                  when 'year' then @breweries.sort_by(&:year)
                  when 'active' then @breweries.sort_by(&:active)
                  when 'beers' then @breweries.sort_by{ |b| b.beers.count }
                  end
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        expire_fragment('brewerylist')
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        expire_fragment('brewerylist')
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    expire_fragment('brewerylist')
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, !brewery.active

    new_status = brewery.active? ? "active" : "retired"

    expire_fragment('brewerylist')

    redirect_to brewery, notice: "Brewery activity status changed to #{new_status}"
  end

  def list
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_with(model: brewery, local: true) do |form| %>
  <% if brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Year</th>
  </tr>
  </thead>

  <tbody>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
        <td></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Back', @brewery, class:'btn btn-primary' %>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<% cache 'brewerylist', skip_digest: true do %>
  <h2>Active</h2>
    <p> Number of active breweries: <%= @active_breweries.count %> </p>
    <%= render 'list', breweries: @active_breweries %>

  <h2>Retired</h2>

    <p> Number of retired breweries: <%= @retired_breweries.count %> </p>
    <%= render 'list', breweries: @retired_breweries %>
<% end %>

<br>

<%= link_to 'New brewery', new_brewery_path, class:'btn btn-primary' if current_user %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <tr>
    <th> <a href="#" id="name">Name</a> </th>
    <th> <a href="#" id="year">Year</a> </th>
    <th> <a href="#" id="beers">Beers</a> </th>
    <th> <a href="#" id="active">Active</a> </th>
  </tr>
</table>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Back', breweries_path, class:'btn btn-primary' %>

app/views/breweries/show.html.erb
<% cache @brewery do %>

  <h2>
    <%= @brewery.name %>
    <% if not @brewery.active %>
      <span class="badge badge-info">retired</span>
    <% end %>
  </h2>

  <p>
    <i> Established in <%= @brewery.year %> </i>
  </p>

  <p>
    Number of beers: <%= @brewery.beers.count %>
  </p>

  <p>
    <% @brewery.beers.each do |beer| %>
      <%= link_to beer.name, beer %>
      <br>
    <% end %>
  </p>

  <p>
    <% if @brewery.ratings.empty? %>
      This brewery has no ratings!
    <% else %>
      <%= "The beers of this brewery have #{pluralize(@brewery.ratings.count, 'rating')} with average score of #{round(@brewery.average_rating.to_s)}" %>
    <% end %>
  </p>

<% end %>

<%= link_to "Change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary"%>
<%= edit_and_destroy_buttons(@brewery) %>
<%= link_to 'Back', breweries_path, class:'btn btn-primary' %>