config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_closed', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :styles
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :places, only: [:index, :show]
  resource :session, only: [:new, :create, :destroy]
  root 'breweries#index'
  #get 'ratings',  to: 'ratings#index'
  #get 'ratings/new', to: 'ratings#new'
  #post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Breweries', breweries_path, { class: "nav-link" } %>
          </li>      
          <li class="nav-item">
            <%= link_to 'Beers', beers_path, { class: "nav-link" } %>
          </li>     
          <li class="nav-item">
            <%= link_to 'Styles', styles_path, { class: "nav-link" } %>
          </li>   
          <li class="nav-item">
            <%= link_to 'Ratings', ratings_path, { class: "nav-link" } %>
          </li>       
          <li class="nav-item">
            <%= link_to 'Users', users_path, { class: "nav-link" } %>
          </li>  
          <li class="nav-item">
            <%= link_to 'Clubs', beer_clubs_path, { class: "nav-link" } %>
          </li>   
          <li class="nav-item">
            <%= link_to 'Beer place search', places_path, { class: "nav-link" } %>
          </li> 
          <% if current_user %>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username %>
            </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "My page", current_user, { class: "dropdown-item" } %>
                <%= link_to "Rate a beer", new_rating_path, { class: "dropdown-item" } %>
                <%= link_to "Join a club", new_membership_path, { class: "dropdown-item" } %>
                <div class="dropdown-divider"></div>
                <%= link_to 'Sign out', signout_path, { class: "dropdown-item", method: :delete } %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', signin_path, { class: "nav-link" } %>
            </li>  
            <li class="nav-item">
              <%= link_to 'Sign up', signup_path, { class: "nav-link" } %>
            </li>                        
          <% end %>                            
        </ul>
      </div>
    </nav>

    <div class="container">
      <% if notice %>
        <div class="alert alert-primary" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <div class="row">
        <div class="col-sm-8">
          <%= yield %>
        </div>
        <div class="col-sm-4">
          <img
            src="http://www.cs.helsinki.fi/u/mluukkai/wadror/pint.jpg"
            width="200"
            style="padding-top:30px"
          >
        </div>
      </div>
    </div>

  </body>
</html>